name: Angular build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - uses: actions/checkout@v3
      with:
        path: sa-new-ui-ts
    - uses: actions/checkout@v3
      with:
        repository: Sanlyty/sa-overview-svelte
        token: ${{ secrets.GH_PAT }}
        path: sa-overview-svelte
    - run: yarn
      working-directory: sa-overview-svelte
    - run: yarn build
      working-directory: sa-overview-svelte
    - run: npm i
      working-directory: sa-new-ui-ts
    - run: npm run build
      working-directory: sa-new-ui-ts
    - name: Create the release.zip file
      run: zip -r ../release.zip .
      working-directory: sa-new-ui-ts/dist/
    - uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./sa-new-ui-ts/release.zip
        asset_name: release.zip
        asset_content_type: application/zip
